---
title: "Vocab_gen_t_test"
author: "Aman Arora"
date: "4/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(text2vec)
library(glmnet)
library(slam)
```


```{r}
train = read.table("alldata.tsv",
                   stringsAsFactors = FALSE,
                   header = TRUE)
train = train [,c("id","sentiment","review")]

#1. Clean up HTML tags
train$review = gsub('<.*?>', ' ', train$review)

#2. Tokenizaton
stop_words = c("i", "me", "my", "myself", 
               "we", "our", "ours", "ourselves", 
               "you", "your", "yours", 
               "their", "they", "his", "her", 
               "she", "he", "a", "an", "and",
               "is", "was", "are", "were", 
               "him", "himself", "has", "have", 
               "it", "its", "the", "us")
it_train = itoken(train$review,
                  preprocessor = tolower, 
                  tokenizer = word_tokenizer)
#3. Create Vocab
tmp.vocab = create_vocabulary(it_train, 
                              stopwords = stop_words, 
                              ngram = c(1L,4L))
#4. Prune vocab
tmp.vocab = prune_vocabulary(tmp.vocab, term_count_min = 10,
                             doc_proportion_max = 0.5,
                             doc_proportion_min = 0.001)

#5. Create DTM
dtm_train  = create_dtm(it_train, vocab_vectorizer(tmp.vocab))

#6. Use Lasso to trim the vocab

v.size = dim(dtm_train)[2]
ytrain = train$sentiment

summ = matrix(0, nrow=v.size, ncol=4)
summ[,1] = colapply_simple_triplet_matrix(
  as.simple_triplet_matrix(dtm_train[ytrain==1, ]), mean)
summ[,2] = colapply_simple_triplet_matrix(
  as.simple_triplet_matrix(dtm_train[ytrain==1, ]), var)
summ[,3] = colapply_simple_triplet_matrix(
  as.simple_triplet_matrix(dtm_train[ytrain==0, ]), mean)
summ[,4] = colapply_simple_triplet_matrix(
  as.simple_triplet_matrix(dtm_train[ytrain==0, ]), var)

n1 = sum(ytrain); 
n = length(ytrain)
n0 = n - n1

myp = (summ[,1] - summ[,3])/
  sqrt(summ[,2]/n1 + summ[,4]/n0)

```

```{r}
words = colnames(dtm_train)
id = order(abs(myp), decreasing=TRUE)[1:200]
pos.list = words[id[myp[id]>0]]
neg.list = words[id[myp[id]<0]]
```


```{r}
myvocab = words[id]
write(myvocab, file = "myvocab.txt", sep = '\t')

```



